# Generated by Django 4.2 on 2023-04-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
